//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazOkuluDersler
{


    public partial class WebForm1
    {

        protected global::System.Web.UI.HtmlControls.HtmlForm Form1;

        protected global::System.Web.UI.WebControls.TextBox TxtAd;

        protected global::System.Web.UI.WebControls.TextBox TxtSoyad;

        protected global::System.Web.UI.WebControls.TextBox TxtNumara;

        protected global::System.Web.UI.WebControls.TextBox TxtSifre;

        protected global::System.Web.UI.WebControls.TextBox TxtFoto;

        protected global::System.Web.UI.WebControls.Button Button1;
    }
}
